services:
  user_management_api:
    container_name: user_management_api
    build: ./user_management
    image: user_management_api
    ports:
      - 50000:8080
    depends_on:
      - user_management_db
    restart: unless-stopped
    networks:
      - user_management_net

  user_management_db:
    container_name: user_management_db
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: api-db
    restart: unless-stopped
    networks:
      - user_management_net

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 49999:80

networks:
  user_management_net:
    driver: bridge
